get:
  tags:
    - query-suggestions
  operationId: getConfigStatus
  description: >
    Get the status of a Query Suggestion's index.

    The status includes whether the Query Suggestions index is currently in the process of being built, and the last build time.
  parameters:
    - $ref: ../../common/parameters.yml#/IndexName
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            title: Status
            additionalProperties: false
            required:
              - indexName
              - isRunning
              - lastBuiltAt
            properties:
              indexName:
                type: string
                description: The targeted index name.
              isRunning:
                type: boolean
                description: true if the Query Suggestions index is running.
              lastBuiltAt:
                type: string
                format: data-time
                description: Date and time of the last build.
    '401':
      $ref: ../../common/responses/Unauthorized.yml
    '403':
      $ref: ../../common/responses/MethodNotAllowed.yml
    '500':
      $ref: ../../common/responses/InternalError.yml
