post:
  tags:
    - query-suggestions
  operationId: createConfig
  description: Create a configuration of a Query Suggestions index. There's a limit of 100 configurations per application.
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../common/parameters.yml#/QuerySuggestionsIndexWithIndexParam
  responses:
    '200':
      $ref: ../../common/responses/Success.yml
    '400':
      $ref: ../../common/responses/BadRequest.yml
    '401':
      $ref: ../../common/responses/Unauthorized.yml
    '403':
      $ref: ../../common/responses/MethodNotAllowed.yml
    '422':
      $ref: ../../common/responses/StatusUnprocessableEntity.yml
    '500':
      $ref: ../../common/responses/InternalError.yml

get:
  tags:
    - query-suggestions
  operationId: getAllConfigs
  description: >
    Get all the configurations of Query Suggestions.

    For each index, you get a block of JSON with a list of its configuration settings.
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: ../common/schemas/QuerySuggestionsIndex.yml#/QuerySuggestionsIndex
    '401':
      $ref: ../../common/responses/Unauthorized.yml
    '403':
      $ref: ../../common/responses/MethodNotAllowed.yml
    '422':
      $ref: ../../common/responses/StatusUnprocessableEntity.yml
    '500':
      $ref: ../../common/responses/InternalError.yml
