put:
  tags:
    - search
  operationId: setDictionarySettings
  description: Set dictionary settings.
  summary: Set dictionary settings.
  requestBody:
    required: true
    content:
      application/json:
        schema:
          title: dictionarySettingsRequest
          type: object
          additionalProperties: false
          description: Disable the builtin Algolia entries for a type of dictionary per language.
          required:
            - disableStandardEntries
          properties:
            disableStandardEntries:
              $ref: 'common/parameters.yml#/standardEntries'
  responses:
    '200':
      $ref: ../../../common/responses/UpdatedAt.yml
    '400':
      $ref: ../../../common/responses/BadRequest.yml
    '402':
      $ref: ../../../common/responses/FeatureNotEnabled.yml
    '403':
      $ref: ../../../common/responses/MethodNotAllowed.yml
    '404':
      $ref: ../../../common/responses/IndexNotFound.yml

get:
  tags:
    - search
  operationId: getDictionarySettings
  description: Retrieve dictionaries settings.
  summary: Retrieve dictionaries settings. The API stores languages whose standard entries are disabled. Fetch settings does not return false values.
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            title: getDictionarySettingsResponse
            additionalProperties: false
            type: object
            required:
              - disableStandardEntries
            properties:
              disableStandardEntries:
                $ref: 'common/parameters.yml#/standardEntries'
    '400':
      $ref: ../../../common/responses/BadRequest.yml
    '402':
      $ref: ../../../common/responses/FeatureNotEnabled.yml
    '403':
      $ref: ../../../common/responses/MethodNotAllowed.yml
    '404':
      $ref: ../../../common/responses/IndexNotFound.yml
