name: Checks

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        id: setup
        uses: ./.github/actions/setup

      - name: Lint GitHub actions
        run: yarn github-actions:lint

    outputs:
      RUN_SPECS: ${{ steps.setup.outputs.RUN_SPECS }}
      SPECS_MATRIX: ${{ steps.setup.outputs.SPECS_MATRIX }}

      RUN_JS: ${{ steps.setup.outputs.RUN_JS }}
      JS_MATRIX: ${{ steps.setup.outputs.JS_MATRIX }}

      RUN_JAVA: ${{ steps.setup.outputs.RUN_JAVA }}
      JAVA_MATRIX: ${{ steps.setup.outputs.JAVA_MATRIX }}

      RUN_CTS: ${{ steps.setup.outputs.RUN_CTS }}

  specs:
    runs-on: ubuntu-20.04
    needs: setup
    if: ${{ always() && needs.setup.outputs.RUN_SPECS == 'true' }}
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.SPECS_MATRIX) }}
    steps:
      - uses: actions/checkout@v2

      - name: Restore cache
        uses: ./.github/actions/cache

      - name: Cache ${{ matrix.client }} spec
        id: cache
        uses: actions/cache@v2
        with:
          path: '/home/runner/work/api-clients-automation/api-clients-automation/specs/dist/${{ matrix.client }}.yml'
          key: ${{ runner.os }}-${{ matrix.client }}-specs-${{ hashFiles(format('specs/{0}/**', matrix.client)) }}

      - name: Building ${{ matrix.client }} specs
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn build:specs ${{ matrix.client }}

  client_javascript:
    runs-on: ubuntu-20.04
    needs:
      - setup
      - specs
    if: ${{ always() && needs.setup.outputs.RUN_JS == 'true' }}
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.JS_MATRIX) }}
    steps:
      - uses: actions/checkout@v2

      - name: Restore cache
        uses: ./.github/actions/cache
        with:
          job: client
          spec: ${{ matrix.client.name }}

      - name: Cache ${{ matrix.client.name }} client
        id: cache
        uses: actions/cache@v2
        with:
          path: '/home/runner/work/api-clients-automation/api-clients-automation/${{ matrix.client.folder }}/dist'
          key: ${{ runner.os }}-1-js-client-${{ matrix.client.name }}-${{ hashFiles(format('{0}/**', matrix.client.folder)) }}-${{ hashFiles(format('specs/dist/{0}.yml', matrix.client.name)) }}

      - name: Generate ${{ matrix.client.name }} client
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn generate javascript ${{ matrix.client.name }}

      - name: Check diff with pushed client
        if: steps.cache.outputs.cache-hit != 'true'
        run: exit $(git status --porcelain ${{ matrix.client.folder }} | wc -l)

      - name: Build ${{ matrix.client.name }} client
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn build:clients javascript ${{ matrix.client.name }}

  client_java:
    runs-on: ubuntu-20.04
    needs:
      - setup
      - specs
    if: ${{ always() && needs.setup.outputs.RUN_JAVA == 'true' }}
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.JAVA_MATRIX) }}
    steps:
      - uses: actions/checkout@v2

      - name: Restore cache
        uses: ./.github/actions/cache
        with:
          job: client
          language: java
          spec: ${{ matrix.client.name }}

      - name: Cache ${{ matrix.client.name }} client
        id: cache
        uses: actions/cache@v2
        with:
          path: '/home/runner/work/api-clients-automation/api-clients-automation/${{ matrix.client.folder }}/target'
          key: ${{ runner.os }}-1-java-client-${{ matrix.client.name }}-${{ hashFiles(format('{0}/**', matrix.client.folder)) }}-${{ hashFiles(format('specs/dist/{0}.yml', matrix.client.name)) }} }}

      - name: Generate ${{ matrix.client.name }} client
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn generate java ${{ matrix.client.name }}

      - name: Check diff with pushed client
        if: steps.cache.outputs.cache-hit != 'true'
        run: exit $(git status --porcelain ${{ matrix.client.folder }} | wc -l)

      - name: Build ${{ matrix.client.name }} client
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn build:clients java ${{ matrix.client.name }}

  cts:
    runs-on: ubuntu-20.04
    needs:
      - client_javascript
      - client_java
    if: ${{ always() && needs.setup.outputs.RUN_CTS == 'true' }}
    steps:
      - uses: actions/checkout@v2

      - name: Restore cache
        id: restore
        uses: ./.github/actions/cache
        with:
          job: cts

      - name: Generate CTS
        run: yarn cts:generate

      - name: Run CTS
        run: yarn cts:test
