indexSettings:
  description: The Algolia index settings.
  allOf:
    - $ref: '#/baseIndexSettings'
    - $ref: '#/indexSettingsAsSearchParams'

baseIndexSettings:
  type: object
  additionalProperties: false
  properties:
    replicas:
      type: array
      items:
        type: string
      description: Creates replicas, exact copies of an index.
      default: []
    paginationLimitedTo:
      type: integer
      description: Set the maximum number of hits accessible via pagination.
      default: 1000
    disableTypoToleranceOnWords:
      type: array
      items:
        type: string
      description: A list of words for which you want to turn off typo tolerance.
      default: []
    attributesToTransliterate:
      type: array
      items:
        type: string
      description: Specify on which attributes to apply transliteration.
    camelCaseAttributes:
      type: array
      items:
        type: string
      description: List of attributes on which to do a decomposition of camel case words.
      default: []
    decompoundedAttributes:
      type: object
      additionalProperties: true
      description: Specify on which attributes in your index Algolia should apply word segmentation, also known as decompounding.
      default: {}
    indexLanguages:
      type: array
      items:
        type: string
      description: Sets the languages at the index level for language-specific processing such as tokenization and normalization.
      default: []
    filterPromotes:
      type: boolean
      description: Whether promoted results should match the filters of the current search, except for geographic filters.
      default: false
    disablePrefixOnAttributes:
      type: array
      items:
        type: string
      description: List of attributes on which you want to disable prefix matching.
      default: []
    allowCompressionOfIntegerArray:
      type: boolean
      description: Enables compression of large integer arrays.
      default: false
    numericAttributesForFiltering:
      type: array
      items:
        type: string
      description: List of numeric attributes that can be used as numerical filters.
      default: []
    userData:
      type: object
      additionalProperties: true
      description: Lets you store custom data in your indices.
      default: {}

indexSettingsAsSearchParams:
  type: object
  additionalProperties: false
  properties:
    searchableAttributes:
      type: array
      items:
        type: string
      description: The complete list of attributes used for searching.
      default: []
    attributesForFaceting:
      type: array
      items:
        type: string
      description: The complete list of attributes that will be used for faceting.
      default: []
    unretrievableAttributes:
      type: array
      items:
        type: string
      description: List of attributes that can't be retrieved at query time.
      default: []
    attributesToRetrieve:
      type: array
      items:
        type: string
      description: This parameter controls which attributes to retrieve and which not to retrieve.
      default: ['*']
    restrictSearchableAttributes:
      type: array
      items:
        type: string
      description: Restricts a given query to look in only a subset of your searchable attributes.
      default: []
    ranking:
      type: array
      items:
        type: string
      description: Controls how Algolia should sort your results.
      default:
        - 'typo'
        - 'geo'
        - 'words'
        - 'filters'
        - 'proximity'
        - 'attribute'
        - 'exact'
        - 'custom'
    customRanking:
      type: array
      items:
        type: string
      description: Specifies the custom ranking criterion.
      default: []
    relevancyStrictness:
      type: integer
      description: Controls the relevancy threshold below which less relevant results aren't included in the results.
      default: 100
    attributesToHighlight:
      type: array
      items:
        type: string
      description: List of attributes to highlight.
    attributesToSnippet:
      type: array
      items:
        type: string
      description: List of attributes to snippet, with an optional maximum number of words to snippet.
      default: []
    highlightPreTag:
      type: string
      description: The HTML string to insert before the highlighted parts in all highlight and snippet results.
      default: '<em>'
    highlightPostTag:
      type: string
      description: The HTML string to insert after the highlighted parts in all highlight and snippet results.
      default: '</em>'
    snippetEllipsisText:
      type: string
      description: String used as an ellipsis indicator when a snippet is truncated.
      default: '…'
    restrictHighlightAndSnippetArrays:
      type: boolean
      description: Restrict highlighting and snippeting to items that matched the query.
      default: false
    hitsPerPage:
      $ref: '#/hitsPerPage'
    minWordSizefor1Typo:
      type: integer
      description: Minimum number of characters a word in the query string must contain to accept matches with 1 typo.
      default: 4
    minWordSizefor2Typos:
      type: integer
      description: Minimum number of characters a word in the query string must contain to accept matches with 2 typos.
      default: 8
    typoTolerance:
      type: string
      enum: [true, false, 'min', 'strict']
      description: Controls whether typo tolerance is enabled and how it is applied.
      default: true
    allowTyposOnNumericTokens:
      type: boolean
      description: Whether to allow typos on numbers ("numeric tokens") in the query string.
      default: true
    disableTypoToleranceOnAttributes:
      type: array
      items:
        type: string
      description: List of attributes on which you want to disable typo tolerance.
      default: []
    separatorsToIndex:
      type: string
      description: Control which separators are indexed.
      default: ''
    ignorePlurals:
      type: string
      description: Treats singular, plurals, and other forms of declensions as matching terms.
      default: false
    removeStopWords:
      type: string
      description: Removes stop (common) words from the query before executing it.
      default: false
    keepDiacriticsOnCharacters:
      type: string
      description: List of characters that the engine shouldn't automatically normalize.
      default: ''
    queryLanguages:
      type: array
      items:
        type: string
      description: Sets the languages to be used by language-specific settings and functionalities such as ignorePlurals, removeStopWords, and CJK word-detection.
      default: []
    decompoundQuery:
      type: boolean
      description: Splits compound words into their composing atoms in the query.
      default: true
    enableRules:
      type: boolean
      description: Whether Rules should be globally enabled.
      default: true
    enablePersonalization:
      type: boolean
      description: Enable the Personalization feature.
      default: false
    queryType:
      type: string
      enum: ['prefixLast', 'prefixAll', 'prefixNone']
      description: Controls if and how query words are interpreted as prefixes.
      default: 'prefixLast'
    removeWordsIfNoResults:
      type: string
      enum: ['none', 'lastWords', 'firstWords', 'allOptional']
      description: Selects a strategy to remove words from the query when it doesn't match any hits.
      default: 'none'
    advancedSyntax:
      type: boolean
      description: Enables the advanced query syntax.
      default: false
    optionalWords:
      type: array
      items:
        type: string
      description: A list of words that should be considered as optional when found in the query.
      default: []
    disableExactOnAttributes:
      type: array
      items:
        type: string
      description: List of attributes on which you want to disable the exact ranking criterion.
      default: []
    exactOnSingleWordQuery:
      type: string
      enum: ['attribute', 'none', 'word']
      description: Controls how the exact ranking criterion is computed when the query contains only one word.
      default: 'attribute'
    alternativesAsExact:
      type: array
      items:
        type: string
        enum: ['ignorePlurals', 'singleWordSynonym', 'multiWordsSynonym']
      description: List of alternatives that should be considered an exact match by the exact ranking criterion.
      default: ['ignorePlurals', 'singleWordSynonym']
    advancedSyntaxFeatures:
      type: array
      items:
        type: string
        enum: ['exactPhrase', 'excludeWords']
      description: Allows you to specify which advanced syntax features are active when ‘advancedSyntax' is enabled.
      default: ['exactPhrase', 'excludeWords']
    distinct:
      type: integer
      minimum: 0
      maximum: 4
      description: Enables de-duplication or grouping of results.
      default: 0
    synonyms:
      type: boolean
      description: Whether to take into account an index's synonyms for a particular search.
      default: true
    replaceSynonymsInHighlight:
      type: boolean
      description: Whether to highlight and snippet the original word that matches the synonym or the synonym itself.
      default: false
    minProximity:
      type: integer
      minimum: 1
      maximum: 7
      description: Precision of the proximity ranking criterion.
      default: 1
    responseFields:
      type: array
      items:
        type: string
      description: Choose which fields to return in the API response. This parameters applies to search and browse queries.
      default: []
    maxFacetHits:
      $ref: '#/maxFacetHits'
    attributeCriteriaComputedByMinProximity:
      type: boolean
      description: When attribute is ranked above proximity in your ranking formula, proximity is used to select which searchable attribute is matched in the attribute ranking stage.
      default: false
    renderingContent:
      type: object
      description: Content defining how the search interface should be rendered. Can be set via the settings for a default value and can be overridden via rules.
      default: {}

maxFacetHits:
  type: integer
  description: Maximum number of facet hits to return during a search for facet values. For performance reasons, the maximum allowed number of returned values is 100.
  maximum: 100
  default: 10

hitsPerPage:
  type: integer
  description: Set the number of hits per page.
  default: 20
